name: py37
dependencies:
- python=3.7

- pip:
  - requests>=2.9.1
  - sphinx==1.7.4
  - sphinx-autobuild==0.7.1
  - git+https://github.com/pytorch/pytorch_sphinx_theme.git#egg=pytorch_sphinx_theme
  - git+https://github.com/hagenw/sphinxcontrib-katex.git#egg=sphinxcontrib.katex